### ISSUE TITLE
Travis Integration

### ISSUE THREAD

**Issue by AnBucquet** [neuropoly/ivado-medical-imaging#127]
As mentioned during the last meeting, it has been decided to use [Travis CI](https://travis-ci.org/) instead of Github actions. 

I guess that the integration of [ReadTheDocs](https://readthedocs.org/) can be done at the same time?

**Comment by jcohenadad** [comment]
> I guess that the integration of ReadTheDocs can be done at the same time?

i would do 2 separate PRs
