### ISSUE TITLE
Post-processing

### ISSUE THREAD

**Issue by charleygros** [neuropoly/ivado-medical-imaging#135]
A key feature that we are currently missing is post-processing pipeline.

Some tools could be implemented and integrated in our testing pipeline:
- basic image processing to remove false positive ?
- basic image processing to fill holes ?
- lesion filtering based on uncertainty measures ?
- segmentation adjustment with CRF postprocessing fed with uncertainty measures and soft segmentations

**Comment by jcohenadad** [comment]
Excellent point, which we should probably discuss during our meeting today
