### ISSUE TITLE
Create a function to perform a one-subject segmentation

### ISSUE THREAD

**Issue by charleygros** [neuropoly/ivado-medical-imaging#154]
Create a function to perform a one-subject segmentation.

The function would have the following inputs: (i) path to image, (ii) path to save the segmentation, (iii) path to trained model. This function could potentially call a function that deals with numpy arrays and actually performs the segmentation.

**Comment by jcohenadad** [comment]
i would leave the image parsing/io to the CLI function, and have the ivadomed package take image objects as inputs, and send back an image object. That way we can clearly separate the ivadomed library from SCT's CLI (which is what we have been trying to converge to).

regarding training, i understand this becomes more complicated, so we could definitely create a CLI wrapper inside the ivadomed library (which would take paths as inputs).

**Comment by charleygros** [comment]
Sounds good.

The thing is our loader receives a list of image bids_paths as input. Will try to see how we can work around this.

**Comment by jcohenadad** [comment]
> The thing is our loader receives a list of image bids_paths as input. Will try to see how we can work around this.

hum, i see... would it be possible to call the loader from the CLI, and then pass the image object to the function that does the inference? (pardon my ignorance-- i should spend some time studying the code ;-) )

**Comment by charleygros** [comment]
> hum, i see... would it be possible to call the loader from the CLI, and then pass the image object to the function that does the inference? (pardon my ignorance-- i should spend some time studying the code ;-) )

Mmm that could be a solution:
1. Call the loader from the CLI
2. Stack the slices
3. call the `ivadomed.utils.segment_volume` function
4. Undo the transforms on the segmented slices within the CLI

**Comment by charleygros** [comment]
To anticipate Uncertainty things --> we will loop across steps # (1, 2, 3, 4) to collect the MC samples --> generate soft segmentation, uncertainty measures etc.

**Comment by jcohenadad** [comment]
> 4. Undo the transforms on the segmented slices within the CLI

i anticipate some issues with that. We should probably have the function output the segmentation in the same physical space as the input image, no?

**Comment by charleygros** [comment]
> > 1. Undo the transforms on the segmented slices within the CLI
> 
> i anticipate some issues with that. We should probably have the function output the segmentation in the same physical space as the input image, no?

The do_transforms are perform during step 1 & 2, out of the function --> That's why it made more sense to me to perform the undo_transforms after the segment_function, so that the function output the segmentation in the same physical space as the input data.

**Comment by jcohenadad** [comment]
ah! i see. So if I understand correctly it would look like this:

**CLI:**
~~~
im_object = open(file_name)
seg_object = ivadomed.utils.segment_volume(im_object)
~~~

**ivadomed.utils.segment_volume:**
~~~
im_object_transfo = func_transfo.do(im_object)
im_seg = segment(im_object_transfo)
return func_transfo.undo(im_object_transfo)
~~~

**Comment by charleygros** [comment]
This could work! I had in mind something slightly different:

### CLI:

dataset = ivadomed.loader.load([file_name])
dataset_transfo = ivadomed.transforms.do(dataset)
dataset_seg = ivadomed.utils.segment_volume(dataset_transfo)
seg_object = ivadomed.transforms.undo(dataset_seg)

**Comment by jcohenadad** [comment]
We should try to converge towards a Python library, where the CLI is only there to provide an "interface" with the user, meaning: it should only pass file names and the backend (i.e., python's library) does the rest. That way, we can easily replace the CLI script with, let's say, a GUI. 

That being said, I'm not 100% confident so let's discuss it during tomorrow's SCT meeting (could you pls add it to the agenda?). Thx!

**Comment by charleygros** [comment]
> We should try to converge towards a Python library, where the CLI is only there to provide an "interface" with the user, meaning: it should only pass file names and the backend (i.e., python's library) does the rest. That way, we can easily replace the CLI script with, let's say, a GUI.

Sorry, I certainly misunderstood this [message](https://github.com/neuropoly/ivado-medical-imaging/issues/154#issuecomment-596790244).

In that case, it could be as simple as this:
**CLI**
```
seg_im_object = ivadomed.utils.segment_volume(model_fname, image_fname)
```
`seg_im_object` being a numpy array in the same orientation and resolution than `Image(image_fname)`. But we could also return a nifti_fname --> to discuss.

**ivadomed.utils.segment_volume:**
```
model = torch.load(model_fname)
dataset = ivadomed.loader.load([image_fname])
dataset_transfo = ivadomed.transforms.do(dataset)
dataset_seg = segment(dataset_transfo)
seg_im = ivadomed.transforms.undo(dataset_seg)
return seg_im
```
