### ISSUE TITLE
Set a convention for docstrings

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/ivado-medical-imaging#156]
I suggest either the [Google Python style](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/index.html#google-vs-numpy) or the [sphinx convention](https://sphinx-rtd-tutorial.readthedocs.io/en/latest/docstrings.html#the-sphinx-docstring-format)

Also see [PEP257 docstring convention](https://www.python.org/dev/peps/pep-0257/). 

Once we agree on a convention, we should update: https://github.com/neuropoly/ivado-medical-imaging/blob/master/CONTRIBUTING.md#developing

**Comment by charleygros** [comment]
I do have a slight preference for the Google Python style.
