### ISSUE TITLE
Strange results with latest t2s model

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/ivado-medical-imaging#168]
Using ivadomed (d3bf0d6a87e368c7ee9984e092c41bd445081dba), trying `segment_volume()` on `sct_testing_data/t2s/t2s.nii.gz`, i get the following results:

![anim](https://user-images.githubusercontent.com/2482071/77217700-c5bbaa00-6afa-11ea-8cae-4677863c4fef.gif)

**Comment by charleygros** [comment]
It works okay on `sct_example_data/t2s/t2s.nii.gz` but I just realised you tested it on `sct_testing_data` --> Will try this.
It is likely to be because of the small image size in the axial plane.

**Comment by charleygros** [comment]
I am able to reproduce :+1: 

Same results with or without the ROI.

Likely to be due to the padding / resampling. Will investigate this!

**Comment by charleygros** [comment]
By doing some plot just after the model prediction --> everything works as expected --> which means that the issue is later in the process. Padding, resampling seem to work well.

![01](https://user-images.githubusercontent.com/14353425/77374556-1ebb6480-6dbf-11ea-91ee-4be32c98279c.png)

**Comment by charleygros** [comment]
While after the `undo_transforms` we get:
![01](https://user-images.githubusercontent.com/14353425/77375439-91c5da80-6dc1-11ea-8730-b0ad4cf1f4bd.png)

I will break then down to identify the one which causes the issue.
