### ISSUE TITLE
Travis tests not running

### ISSUE THREAD

**Issue by olix86** [neuropoly/ivado-medical-imaging#175]
Unless I'm missing something huge, it looks like Travis tests are not working since +2 months. For some reason the `pytest` command ends up on the same like as the `echo` on the line before, so `pytest` is simply echoed and not executed.

Current situation :
![image](https://user-images.githubusercontent.com/5721601/77812170-ebeec600-7075-11ea-82e6-7bc248c4d5d6.png)

Latest commit @AnBucquet on the travis config shows the same thing : [link](https://travis-ci.org/github/neuropoly/ivado-medical-imaging/builds/637506140)

**Comment by jcohenadad** [comment]
@olix86 can we close this issue?

**Comment by olix86** [comment]
Well it's fixed by #186 but tests are now failling since they use too much RAM
