### ISSUE TITLE
segment_volume: fname_roi parameter is obscure

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/ivado-medical-imaging#177]
in commit 6bc50021eefe454db0b953fe67cb6f047ebeb2e7, the docstrings says:

~~~
"Binary image filename (e.g. .nii.gz) defining a region of interest, e.g. spinal cord centerline, used to crop the image prior to segment it if provided."
~~~
Reading this, I assumed that fname_roi is a centerline, around which a 2D square matrix is estimated slice by slice, centered on the center of mass of the provided centerline, and this square matrix is used as input for the segmentation.

Later, this line (https://github.com/neuropoly/ivado-medical-imaging/blob/master/ivadomed/utils.py#L714) mentions:
~~~
    # If fname_roi provided, then remove slices without ROI
~~~
So, I am a bit confused because I originally thought that that fname_roi was used to crop in the axial plane, but now it seems like it is used to crop along the S-I axis (i.e. remove empty slices).

Before that line, the function `MRI2DSegmentationDataset` does incorporate `fname_roi` inside the variable `filename_pairs`, but we then loose track of the specific purpose of `fname_roi` (`MRI2DSegmentationDataset`'s docstrings talks about ROI but we don't know what it is used for)

I would suggest to either rename and/or clarify the `fname_roi` variable.

**Comment by charleygros** [comment]
> So, I am a bit confused because I originally thought that that fname_roi was used to crop in the axial plane, but now it seems like it is used to crop along the S-I axis (i.e. remove empty slices).

It actually does both: (1) for the slices when centerline is available --> it crop around it (2) otherwise, the slice is not included in the segmentation process (--> output zeros-like slice).

Potential applications:
(i) image containing brain section --> centerline stops at the PMJ
(ii) lesion segmentation only on slices where the SC has been detected

So, this file is essentially used to define a ROI around the cord: in the axial plane for cropping and potentially in the IS axis for slice removal.
We should indeed clarify this in the docstring.

**Comment by jcohenadad** [comment]
> Potential applications:
(i) image containing brain section --> centerline stops at the PMJ
(ii) lesion segmentation only on slices where the SC has been detected

I guess (iii) cropping around the centerline is another one

I would be tempted to suggest renaming the variable fname_centerline, because this file is effectively a centerline, right?  The fact that we ignore slices where the centerline is not defined is a corollary benefit of this file, but its primary purpose is to crop around it, right?

**Comment by charleygros** [comment]
> I guess (iii) cropping around the centerline is another one

Oh yes of course, I was not clear: I was referring to the IS slice removal. But yes.
 
> I would be tempted to suggest renaming the variable fname_centerline, because this file is effectively a centerline, right? The fact that we ignore slices where the centerline is not defined is a corollary benefit of this file, but its primary purpose is to crop around it, right?

I would prefer to keep `roi` over `centerline` --> `centerline` mainly relates to the SC, while `ivadomed` could be used for other organs, for instance:
- brain data --> `fname_roi=skull_mask.nii.gz` --> it will remove the top and bottom slices + crop axial slices of interest with a given size around the skull.
- liver data tu segment liver tumour -->  `fname_roi=liver_mask.nii.gz` --> etc.

**Comment by jcohenadad** [comment]
alternatively: fname_centreroi

**Comment by jcohenadad** [comment]
It was decided to keep the variable name as it is but clarify the docstring
