### ISSUE TITLE
Imports or reference missing

### ISSUE THREAD

**Issue by andreanne-lemay** [neuropoly/ivado-medical-imaging#179]
In main:
-AXIS_DCT (should be utils.AXIS_DCT) 
(https://github.com/neuropoly/ivado-medical-imaging/blob/master/ivadomed/main.py#L7270)
(https://github.com/neuropoly/ivado-medical-imaging/blob/master/ivadomed/main.py#L764)
(https://github.com/neuropoly/ivado-medical-imaging/blob/master/ivadomed/main.py#L789)
-torch.nn (https://github.com/neuropoly/ivado-medical-imaging/blob/master/ivadomed/main.py#L211)
-pred_to_nib (should be utils.pred_to_nib)
(https://github.com/neuropoly/ivado-medical-imaging/blob/master/ivadomed/main.py#L760)
(https://github.com/neuropoly/ivado-medical-imaging/blob/master/ivadomed/main.py#L785)

In testing:
Conflict in `test_HeMIS` when `from ivadomed.utils import SliceFilter` with the import in loader (https://github.com/neuropoly/ivado-medical-imaging/blob/master/ivadomed/loader.py#L3)
![image (1)](https://user-images.githubusercontent.com/49137243/78053472-a7517c00-734e-11ea-8c1e-9202d51a7933.png)

-Need to `import torch` in the following: `test_inference`, `test_HeMIS`, `test_training`, `undo_transform`, `test_sampler`
-In test `test_inference` incorrect call of: pred_to_nib, IvadoMetricManager, threshold_predictions
-`import matplotlib.pyplot as plt` in test `test_undoTrans`

**Comment by olix86** [comment]
- [x] `main`
- [ ] `testing/`
