### ISSUE TITLE
Integration of medicaltorch in ivadomed

### ISSUE THREAD

**Issue by andreanne-lemay** [neuropoly/ivado-medical-imaging#198]
Since the fork neuropoly/medicaltorch is starting to differ a lot from the original medicaltorch repository, the fork will be integrated to the ivado-medical-imaging repository. This will centralize the code and avoid to make changes to 2 different repositories.

Different steps for the medicaltorch integration:
- [x] Merge metrics (dice, recall, specificity, etc.) 
- [x] Integrate filters
- [ ] Merge transforms. Currently medicaltorch transforms are parent to ivadomed transforms. Moving the transforms will remove this relation. Following class should be moved in ivadomed/transforms.py
-UndoTransform
-ToPIL
-NormalizeInstance
-NormalizeInstance3D
-ToTensor
-StackTensors
-Crop2D
-CenterCrop2D
-ROICrop2D
-RandomRotation
-RandomRotation3D
-RandomReverse3D
-RandomAffine
-ElasticTransform
-Resample
- [ ] Move following classes in medicaltorch/datasets.py to ivadomed/loader.py
-SegmentationPair2D 
-MRI2DSegmentationDataset
-MRI3DSubVolumeSegmentationDataset
-mt_collate (function)
-SampleMetadata

The ivadomed/loader.py may become too dense. We might want to create a loader_utils.py.

**Comment by jcohenadad** [comment]
> The ivadomed/loader.py may become too dense. We might want to create a loader_utils.py.

👍 anything that could reduce the code in loader (which is already long) is welcome

**Comment by charleygros** [comment]
I even wonder if we should not create a folder `loader` with `core.py`, `utils.py`, `adaptative.py` etc.
Similarly a `model` folder with something like: `core.py`, `unet_2d.py`, `unet_3d.py`, `hemis.py`, `film.py`, `utils.py`. ... one day :)

**Comment by olix86** [comment]
I think we can close this, good job everyone :)
