### ISSUE TITLE
Binarize image prior to applying morphomath operations

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/ivado-medical-imaging#205]
Some postprocessing methods, such as keep_large_objects or fill_holes only work on binary images. So if people want soft output while still benefiting from these algorithms, one solution is to call the thresholding with low value (eg 10e-3), apply morphomath operation, and then use the mask_prediction function to remove the small objects from the soft pred based on the binary output of the morphomath process.

**Comment by charleygros** [comment]
Fixed with #206
