### ISSUE TITLE
Folder imports

### ISSUE THREAD

**Issue by charleygros** [neuropoly/ivado-medical-imaging#212]
In order to reduce the length / complexity of the imports, we could replace:
```python
from ivadomed.loader import utils as imed_loader_utils, adaptative as imed_adaptative, film as imed_film
```
by
```python
from ivadomed import loader as imed_loader
```

To allow this, we would need to add in the [__init__.py](https://github.com/neuropoly/ivado-medical-imaging/blob/master/ivadomed/loader/__init__.py) these following lines:
```python
from loader import *
from adaptative import *
from utils import *
from film import *
```

**Comment by jcohenadad** [comment]
that sounds great!

my suggestion however would be, instead of renaming functions/classes with "imed_" prefix, why not doing:
```python
import ivadomed as imed
import ivadomed.loader

# in the code
imed.loader
```

it takes the same amount of characters, it is more explicit and it allows to use automatic completion within IDE.
