### ISSUE TITLE
segment_volume() sub-optimal results and implement testing

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/ivado-medical-imaging#227]
Based on the latest version of ivadomed (1.0), i noticed sub-optimal results compared to when i ran it a few weeks ago (sorry I don't have records for comparison). More details here: https://github.com/neuropoly/spinalcordtoolbox/pull/2639#issuecomment-629398909

@charleygros maybe you have a clue?

The other purpose of this issue is to suggest implementing a testing routine `utils.segment_volume()` to track possible changes in segmentation output.

**Comment by charleygros** [comment]
It looks like a binarisation of the output has been introduced in one of the PRs recently merged. Will investigate and let you know shortly.

**Comment by charleygros** [comment]
I can reproduce the sub-obtimal results. However this is not due to `utils.segment_volume()` but to the post-processing --> see here below screenshot of result before the postprocessing (ie output of `utils.segment_volume()`).
![Screenshot 2020-05-18 14:53:52](https://user-images.githubusercontent.com/14353425/82175614-9fa66080-9917-11ea-90d5-8fe38fe94c67.png)

**Comment by charleygros** [comment]
I believe the error is coming from the thresholding function as the result is the same independently of the threshold value I enter.

**Comment by charleygros** [comment]
Update: the error is actually not coming from the thresholding function but from `options['threshold']` that is always at 0.9 (ie default value) even if I use the param `-thr 0.1`.

**Comment by charleygros** [comment]
It is likely to come from the mismatch between the parser and DEFAULT params --> `thr` vs `threshold`.
```python
    misc.add_argument(
        "-thr",
        type=float,
        help="Binarize segmentation with specified threshold. Set to 0 for no t$
             "Default value is model-specific and was set during optimization "
             "(more info at https://github.com/sct-pipeline/deepseg-threshold).$
        metavar=sct.utils.Metavar.float)
```
versus
```python
DEFAULTS = {
    'threshold': 0.9,
    'keep_largest_object': True,
    'fill_holes': True,
    }
```

**Comment by charleygros** [comment]
Changes suggested [dc3f610](https://github.com/neuropoly/spinalcordtoolbox/pull/2639/commits/dc3f610858262555db65d77ac266ccaeead7cf3c), which address the issue of under-segmentation.

**Comment by jcohenadad** [comment]
Thank you @charleygros !
