### ISSUE TITLE
Redirect ivadomed.org to RTD's latest version

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/ivado-medical-imaging#248]
The following needs to be done:
- Redirect ivadomed.org to RTD latest version;
- Add link to ivadomed.org at the top of the github's project page

**Comment by jcohenadad** [comment]
@alexfoias you [mentioned it takes 30min for redirection](https://github.com/neuropoly/ivado-medical-imaging/pull/264#issuecomment-637017333), but it's been 2h already and www.ivadomed.org gives me that:
![Screen Shot 2020-06-01 at 4 24 19 PM](https://user-images.githubusercontent.com/2482071/83451059-62b49080-a424-11ea-83ea-fe962bd6db49.png)

Can you please check if everything is in order?

**Comment by alexfoias** [comment]
Sorry about that, there a problem with the configuration I tried multiple things on namecheap and readthedocs last evening without success. I'll fix it during today.

**Comment by alexfoias** [comment]
The proper way of configuring the custom domain in RTD is the following:

- In namecheap, go to your domain, advance DNS and add a ALIAS record with the following info:
| Type         | Host | Value           | TTL  |
|--------------|------|-----------------|------|
| ALIAS Record | @    | readthedocs.io. | 1min |

- In readthedocs, go to your project, Admin, Domains, Add new Domain:
```
Domain: ivadomed.org
Canonical: [x]  This Domain is the primary one where the documentation is served from
Use HTTPS: [x]  Always use HTTPS for this domain
```

**Comment by alexfoias** [comment]
@jcohenadad We can close this issue.
