### ISSUE TITLE
Some pytest tests fail

### ISSUE THREAD

**Issue by andreanne-lemay** [neuropoly/ivado-medical-imaging#251]
Tests in test_transforms.py use randomly generated inputs and ground truths. This causes some tests to fail by time to time ([related comment](https://github.com/neuropoly/ivado-medical-imaging/pull/213#issuecomment-631864898)). These tests should be modified so that they systematically pass. List of tests failing:
- test_NormalizeInstance
- test_DilateGT
- test_RandomRotation
- test_RandomAffine

**Comment by charleygros** [comment]
Duplication: https://github.com/neuropoly/ivado-medical-imaging/issues/236
I am closing #236

**Comment by charleygros** [comment]
Adding another one that is in trouble: `test_RandomShiftIntensity`.

**Comment by jcohenadad** [comment]
Is it fixed by #254?
