### ISSUE TITLE
Revisit performance scores

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/ivado-medical-imaging#45]
The Dice is highly sensitive to the size of the object (e.g., small lesion will highly impact Dice, and potentially be noisy), and the specificity includes voxels of class=0 (to confirm), which brings it to close to 1, which is not informative.

We might want to introduce more representative metrics, such as Hausdorff distance, and only include voxels=1 in the computation of the specificity. Object-based metrics (see [Gros et al 2018](https://paperpile.com/view/a3911a98-1d16-0bac-a8f4-26844d869998)) could also be relevant.

**Comment by charleygros** [comment]
Not sure what we meant here:
> voxels=1 in the computation of the specificity

Can someone help me to remember?
